version: '3.8'

services:
  ai-detection:
    build: .
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
